name: Release

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build
        run: cargo build --release

      - name: Install cargo-wix and WiX Toolset
        shell: pwsh
        run: |
          # Install WiX Toolset
          choco install wixtoolset -y
          $wixPath = Get-ChildItem "C:\Program Files (x86)" -Directory | Where-Object { $_.Name -like "WiX Toolset v*" } | Sort-Object Name -Descending | Select-Object -First 1
          if ($wixPath) {
            $env:Path += ";$($wixPath.FullName)\bin"
          } else {
            Write-Error "WiX Toolset not found in Program Files (x86)"
            exit 1
          }
          # Install cargo-wix
          cargo install cargo-wix

      - name: Build Windows installer with cargo wix
        run: cargo wix --log-level debug
